name: PR Workflow

on:
  push:
    branches:
      - main

jobs:
  check-news-folder:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Check Number of .md Files
      run: |
        cd news
        md_file_count=$(ls -1 *.md | wc -l)

        if [ "$md_file_count" -gt 5 ]; then
          echo "Number of .md files in '/news' folder is over or equal to 5. Starting publish script..."
          cd ..
          chmod +x publish.js

          echo "Publishing Blogs..."
          node ./publish.js

          echo "Back up and Clean up"
          rm -f news/*.md

          # Commit and push changes
          git config --global user.email "bhattacharyasaptarshi2001@gmail.com"
          git config --global user.name "Saptarshi"
          git add -A
          git commit -m "Delete excess .md files"
          git push
        
        else
          echo "Not Enough Articles yet!"
          exit 0
        fi
